apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:10.0-devel
      command: 
      - nvidia-smi
      resources:
        limits:
          nvidia.com/gpu: 1
  nodeSelector:
    nvidia.com/gpu: 'true'